// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*vMTraceMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (v VMTrace) MarshalJSON() ([]byte, error) {
	type VMTrace struct {
		Code hexutil.Bytes `json:"code"`
		Ops  []VMOperation `json:"ops"`
	}
	var enc VMTrace
	enc.Code = v.Code
	enc.Ops = v.Ops
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (v *VMTrace) UnmarshalJSON(input []byte) error {
	type VMTrace struct {
		Code *hexutil.Bytes `json:"code"`
		Ops  []VMOperation  `json:"ops"`
	}
	var dec VMTrace
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Code != nil {
		v.Code = *dec.Code
	}
	if dec.Ops != nil {
		v.Ops = dec.Ops
	}
	return nil
}
